"""
IBM watsonx.ai API Client
Handles communication with watsonx.ai for AI-powered code analysis summaries
"""

import os
import json
from typing import Optional, Dict, Any
from dotenv import load_dotenv

# Load environment variables
load_dotenv()


class WatsonxClient:
    """Client for interacting with IBM watsonx.ai API"""
    
    def __init__(self):
        """Initialize the watsonx client with credentials from environment"""
        self.api_key = os.getenv("WATSONX_API_KEY")
        self.project_id = os.getenv("WATSONX_PROJECT_ID")
        self.url = os.getenv("WATSONX_URL", "https://us-south.ml.cloud.ibm.com")
        self.model_id = os.getenv("WATSONX_MODEL_ID", "ibm/granite-13b-chat-v2")
        self.max_tokens = int(os.getenv("WATSONX_MAX_TOKENS", "500"))
        self.temperature = float(os.getenv("WATSONX_TEMPERATURE", "0.7"))
        
        self._validate_config()
    
    def _validate_config(self):
        """Validate that required configuration is present"""
        if not self.api_key:
            raise ValueError("WATSONX_API_KEY environment variable is required")
        if not self.project_id:
            raise ValueError("WATSONX_PROJECT_ID environment variable is required")
    
    def generate_summary(self, issues: list, score_data: dict, mcp_findings: list) -> str:
        """
        Generate an AI-powered executive summary using watsonx.ai
        
        Args:
            issues: List of code issues found
            score_data: Dictionary containing score and status
            mcp_findings: List of MCP tool findings
            
        Returns:
            AI-generated executive summary as a string
        """
        try:
            # Import here to avoid dependency issues if not installed
            from ibm_watsonx_ai.foundation_models import Model
            from ibm_watsonx_ai.metanames import GenTextParamsMetaNames as GenParams
            
            # Prepare the prompt for watsonx
            prompt = self._create_prompt(issues, score_data, mcp_findings)
            
            # Initialize the model
            model = Model(
                model_id=self.model_id,
                params={
                    GenParams.MAX_NEW_TOKENS: self.max_tokens,
                    GenParams.TEMPERATURE: self.temperature,
                    GenParams.DECODING_METHOD: "greedy"
                },
                credentials={
                    "apikey": self.api_key,
                    "url": self.url
                },
                project_id=self.project_id
            )
            
            # Generate the summary
            response = model.generate_text(prompt=prompt)
            
            return self._format_response(response)
            
        except ImportError:
            return self._fallback_summary(issues, score_data, mcp_findings)
        except Exception as e:
            print(f"Warning: watsonx.ai API call failed: {str(e)}")
            return self._fallback_summary(issues, score_data, mcp_findings)
    
    def _create_prompt(self, issues: list, score_data: dict, mcp_findings: list) -> str:
        """Create a structured prompt for watsonx.ai"""
        
        # Count severity levels
        severity_count = {}
        for issue in issues:
            severity = issue["severity"]
            severity_count[severity] = severity_count.get(severity, 0) + 1
        
        prompt = f"""You are an expert DevOps engineer analyzing code quality metrics. Generate a concise executive summary.

Code Health Metrics:
- Overall Score: {score_data['score']}/100
- Status: {score_data['status']}
- Total Issues: {len(issues)}
- Critical Issues: {severity_count.get('Critical', 0)}
- High Severity: {severity_count.get('High', 0)}
- Medium Severity: {severity_count.get('Medium', 0)}
- Low Severity: {severity_count.get('Low', 0)}
- MCP Tool Findings: {len(mcp_findings)}

Generate a professional executive summary that:
1. Highlights the current code health status
2. Identifies top 3 risk areas
3. Provides actionable recommendations
4. Suggests priority order for fixes

Keep it concise (3-4 paragraphs) and business-focused."""

        return prompt
    
    def _format_response(self, response: str) -> str:
        """Format the watsonx.ai response into markdown"""
        return f"""## watsonx.ai Executive Summary

{response.strip()}

---
*Generated by IBM watsonx.ai using {self.model_id}*
"""
    
    def _fallback_summary(self, issues: list, score_data: dict, mcp_findings: list) -> str:
        """Generate a basic summary when watsonx.ai is not available"""
        severity_count = {}
        for issue in issues:
            severity = issue["severity"]
            severity_count[severity] = severity_count.get(severity, 0) + 1
        
        return f"""## watsonx.ai Executive Summary

⚠️ *Note: Using fallback summary. Configure watsonx.ai credentials for AI-powered analysis.*

The repository was assessed using a Bob-powered engineering workflow supported by MCP-style local tools.

The current code health score is **{score_data['score']}/100**, with the status: **{score_data['status']}**.

### Key Findings:
- **Critical Issues:** {severity_count.get('Critical', 0)}
- **High Severity:** {severity_count.get('High', 0)}
- **Medium Severity:** {severity_count.get('Medium', 0)}
- **Low Severity:** {severity_count.get('Low', 0)}
- **MCP Findings:** {len(mcp_findings)}

### Risk Assessment:
Critical/High issues may affect security, reliability, or runtime stability. Missing documentation reduces maintainability. MCP-style tool checks detected **{len(mcp_findings)}** additional operational findings.

### Recommended Actions:
1. Address critical and high-severity issues first
2. Use IBM Bob to refactor the highest-risk functions
3. Re-run the control tower pipeline to validate improvements
4. Add comprehensive documentation for undocumented functions

---
*To enable AI-powered summaries, configure your watsonx.ai credentials in .env file*
"""


def get_watsonx_client() -> Optional[WatsonxClient]:
    """
    Factory function to get a watsonx client instance
    Returns None if configuration is invalid
    """
    try:
        return WatsonxClient()
    except ValueError as e:
        print(f"Warning: {str(e)}")
        return None

# Made with Bob
